apiVersion: v2
name: cluster-svc
description: lw-idp cluster registry
type: application
version: 0.0.1
appVersion: "0.0.0"
dependencies:
  - name: lw-idp-service
    version: 0.1.0
    repository: "file://../lw-idp-service"
