// Re-export all OpenAPI-generated types for the gateway REST surface.
// Source: dist/openapi/gateway.d.ts (generated by openapi-typescript from openapi/gateway.yaml).
// Consumers: import type { paths, components } from "@lw-idp/contracts/gateway"
export type * from "../dist/openapi/gateway.js";
