apiVersion: v1
kind: Namespace
metadata:
  name: dragonfly-system
---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: df
  namespace: dragonfly-system
spec:
  replicas: 3
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
