releases:
  - name: kube-prometheus-stack
    namespace: observability
    chart: prometheus-community/kube-prometheus-stack
    version: 83.6.0
    values:
      - ../observability/kube-prometheus-stack.yaml

  - name: loki
    namespace: observability
    chart: grafana/loki
    version: 6.55.0
    values:
      - ../observability/loki.yaml

  - name: promtail
    namespace: observability
    chart: grafana/promtail
    version: 6.16.6
    values:
      - ../observability/promtail.yaml
    needs:
      - observability/loki

  - name: tempo
    namespace: observability
    chart: grafana/tempo
    version: 1.24.4
    values:
      - ../observability/tempo.yaml

  - name: trivy-operator
    namespace: trivy-system
    chart: aquasecurity/trivy-operator
    version: 0.31.0
    values:
      - ../trivy/values.yaml
    needs:
      - observability/kube-prometheus-stack

  - name: lw-idp-observability
    namespace: observability
    chart: ../../charts/lw-idp-observability
    needs:
      - observability/kube-prometheus-stack
