releases:
  - name: kube-prometheus-stack
    namespace: observability
    chart: prometheus-community/kube-prometheus-stack
    version: 83.6.0
    values:
      - ../observability/kube-prometheus-stack.yaml
